development:
  adapter: postgresql
  database: tunutrivida_development
  username: user_seven
  password: 7777777
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: tunutrivida_test
  username: user_seven
  password: 7777777
  host: localhost
  port: 5432


production:
  adapter: postgresql
  database: tunutrivida_production
  username: user_seven
  password: 7777777
  host: localhost
  port: 5432
